import os
from PyZOGY.subtract import run_subtraction


def subtract_images(image_list, subtraction_type):
    """Subtract images given in list generated by fakeimage"""

    for subtraction in subtraction_type:
        images = open(image_list)
        for image in images:
            files = image.split(',')
            science_image = files[0]
            science_psf = files[1]
            science_mask = files[2]
            reference_image = files[3]
            reference_psf = files[4]
            reference_mask = files[5][:-1]

        if subtraction == 'PyZOGY':

            if 'None' in science_mask:
                science_mask = ''
            if 'None' in reference_mask:
                reference_mask = ''

            output = science_image.replace('.fits', '.diff.fits')

            run_subtraction(science_image,
                            reference_image,
                            science_psf,
                            reference_psf,
                            output=output,
                            science_mask=science_mask,
                            reference_mask=reference_mask,
                            n_stamps=4)

        elif subtraction == 'hotpants':
            command = 'hotpants -inim {0} -tmplim {1} -outim -{2} imi {3} -tmi {4}' + science_mask.format(
                science_image, reference_image, output, science_mask, reference_mask)

            os.system(command)
